### ISSUE TITLE
Typora img upload None error

### ISSUE THREAD

**Issue by logic-three-body** [Iamxiaozhu/file-uploader-cli#1]
您好作者，我是window10环境，我按操作用npm下载file-uploader-cli，但当我在typora中输入自定义命令fuc时，typora报错 "none" 图片也没有成功上传到指定github仓库
我的config配置(token我就不放了)
{
  "github": {
    "token": "/*mytoken*/",
    "user": "logic-three-body",
    "repo": "imageBase",
    "path": "F:/document/imageBase",
    "branch": "*",
    "jsdelivr": true
  },
  "default": "github"
}
类似这样的，请问我的配置正确吗，麻烦了，谢谢

**Comment by 89171** [comment]
您好，可以修改一下path，path是文件存放在github仓库中哪个目录下。branch是上传到具体哪个分支下，github新建的仓库默认分支都变成了main，所以默认会使用main分支。
已修改Readme描述，很感谢使用和反馈。
